### ISSUE TITLE
Redirect after pressing OK , in the Confirm alert. 

### ISSUE THREAD

**Issue by azlannohara** [t4t5/sweetalert#319] opened 2015-03-23 04:10 UTC
Hello all. I been using the confirm alert.

````
swal({   
title: "Are you sure?",   
text: "You will not be able to recover this imaginary file!",   
type: "warning",   
showCancelButton: true,   
confirmButtonColor: "#DD6B55",   
confirmButtonText: "Yes, delete it!",   
closeOnConfirm: false 
}, 
function()
{   
swal("Deleted!", "Your imaginary file has been deleted.", "success"); });
````

Can I redirect/reload page after the user click OK on ("Deleted!", "Your imaginary file has been deleted.", "success") ?

**Comment by masteradhoc** [comment] 2015-03-25 08:36
Maybe this could help you..
Follow an external link at https://www.ludu.co/lesson/how-to-use-sweetalert

**Comment by azlannohara** [comment] 2015-03-25 08:44
Alright. Thanks!

**Comment by mp3il** [comment] 2015-03-25 22:49
Passing another callback to the second swal seems to be a problem. have you found a solution?

**Comment by t4t5** [comment] 2015-04-01 10:58
I'll close this since it's not an issue.

**Closed by t4t5** 2015-04-01 10:58 UTC

**Comment by mp3il** [comment] 2015-04-01 10:59
@t4t5 - Can the second swal function confirm have a callback function? doesn't seem to work to me.

**Comment by harishtoshniwal** [comment] 2016-06-10 14:04
@t4t5 Hey thanks for SweetAlert :) I found the solution for this issue and sharing it below.
I know its old but i found the solution so i hope it helps anyone.

@mp3il @azlannohara @masteradhoc The problem is the shorthand in the closure. You can do the required(Reload after clicking on "Okay" that appears after successful deletion) by using the below code: 

`$('a.delete-member').click(function() {
	    var memberId = $(this).attr("data-member-id");
	    deleteMember(memberId);
	  });

	  function deleteMember(memberId) {
	    swal({
	      title: "Are you sure?", 
	      text: "Are you sure that you want to delete this member?", 
	      type: "warning",
	      showCancelButton: true,
	      showLoaderOnConfirm: true,
	      closeOnConfirm: false,
	      confirmButtonText: "Yes, delete it!",
	      confirmButtonColor: "#ec6c62"
	    }, function() {
	      $.ajax({
	        url:  "/members/" + memberId + "/archive",
	        type: "POST"
	      })
	      .done(function(data) {
	        swal({
	        	title: "Deleted", 
		      	text: "Member has been successfully deleted", 
		      	type: "success"
	  		},function() {
	  			location.reload();
	  		});
	      })
	      .error(function(data) {
	        swal("Oops", "We couldn't connect to the server!", "error");
	      });
	    });
	  }`

**Comment by Hajmahdikahsan** [comment] 2017-11-25 07:13
I used this code but Show error 
VM1355:23 POST http://localhost:7100/Forces/Delete/5 500 (Internal Server Error)

`function Delete(id) {
        swal({
            title: "Are you sure?", 
            text: "Are you sure that you want to delete this member?", 
            type: "warning",
            showCancelButton: true,
            showLoaderOnConfirm: true,
            closeOnConfirm: false,
            confirmButtonText: "Yes, delete it!",
            confirmButtonColor: "#ec6c62"
        }, function() {
            $.ajax({
                url:  "/Forces/Delete/"+id,
                type: "POST"
            })
            .done(function(data) {
                swal({
                    title: "Deleted", 
                    text: "Member has been successfully deleted", 
                    type: "success"
                },function() {
                    location.reload();
                });
            })
            .error(function(data) {
                swal("Oops", "We couldn't connect to the server!", "error");
            });
        });
    }`

**Comment by shohelic** [comment] 2018-02-19 06:38
@introwit it's working and grate. thanks
