### ISSUE TITLE
Page jumps to top when sweetalert is opened

### ISSUE THREAD

**Issue by caseyWebb** [t4t5/sweetalert#467] opened 2015-10-29 05:35 UTC
Fix in PR #466

**Comment by pennstump** [comment] 2016-01-06 05:43
I am having this same issue.

**Comment by sbolel** [comment] 2016-02-04 09:17
Yep, me too

**Comment by dreyk213** [comment] 2017-03-17 17:01
still actual +1

**Comment by azizk-araneux** [comment] 2017-05-03 12:24
Same issue.

**Comment by t4t5** [comment] 2017-09-08 07:37
Sorry for such a long delay. I believe the issue is fixed in [2.0](https://sweetalert.js.org/guides/#upgrading-from-1x). Please have a look!

**Closed by t4t5** 2017-09-08 07:37 UTC

**Comment by azizk-araneux** [comment] 2017-09-08 08:45
@t4t5 Issue has been resolved. Thank you :)
