### ISSUE TITLE
[BUG] `closeOnConfirm` to false break tab button

### ISSUE THREAD

**Issue by Buom01** [t4t5/sweetalert#544] opened 2016-02-28 13:34 UTC
Hi,
I find a bug (tested in firefox):
in a form, you can press tab to go to the next input, but after this code:

``` JavaScript
swal({
    title: "Simple question",
    closeOnConfirm: false,
},function(){
    window.setTimeout(function(){
        swal("Simple confirmation", "and tab breaking", "success");
    },0);
});
```

you can't use tab button in form anymore :(

**Comment by Buom01** [comment] 2016-02-28 13:38
Temporary solution find in: https://github.com/t4t5/sweetalert/issues/391

**Comment by alex-shamshurin** [comment] 2017-04-03 12:26
The same issue is here. Solution is `window.onkeydown = null` in onClose callback

**Comment by t4t5** [comment] 2017-09-08 06:49
Closing since it's a duplicate of #391. Will investigate soon.

**Closed by t4t5** 2017-09-08 06:49 UTC
