### ISSUE TITLE
After sweetalert Show

### ISSUE THREAD

**Issue by FelipeArruda** [t4t5/sweetalert#526] opened 2016-01-31 21:31 UTC
So, IDK with Im taking a mistake, but when the alert show up I cant move with the key TAB to another input after I press OK, its look to be locked in the same input.

``` javascript
  swal({
                        title: "Buscando cep....",
                        type: "info",
                        showCancelButton: false,
                        showConfirmButton: false,
                        timer: 2000
                    },
                    function(){
                        swal("CEP encontrado!", "", "success");
                    });`

```

**Comment by Buom01** [comment] 2016-02-28 13:38
Temporary solution find in: https://github.com/t4t5/sweetalert/issues/391

**Comment by FelipeArruda** [comment] 2016-02-28 15:05
@Buom01 Thank you bro. I'll try this solution.

**Comment by t4t5** [comment] 2017-09-08 07:03
Duplicate of #391

**Closed by t4t5** 2017-09-08 07:03 UTC
