### ISSUE TITLE
cancelButtonColor

### ISSUE THREAD

**Issue by kidchenko** [t4t5/sweetalert#290] opened 2015-02-21 22:46 UTC
It should be possible to choose the cancel button color equals i choice confirmButtonColor: #DD6B55. (e.g cancelButtonColor: #DD6B55)

This makes intuitive API

**Comment by parterburn** [comment] 2015-03-19 17:25
Dupe of #249

**Comment by kiide** [comment] 2015-03-20 04:36
Sorry, i have open repeat issue, I tried and not work, i try now again!

**Comment by t4t5** [comment] 2017-09-08 08:24
`confirmButtonColor` has been deprecated in favour of a pure CSS approach. To style the cancel button in [SweetAlert 2.0](https://sweetalert.js.org), you target the class `.swal-button--cancel`.

**Closed by t4t5** 2017-09-08 08:24 UTC
