### ISSUE TITLE
ASP.NET Webforms behavior closes after call

### ISSUE THREAD

**Issue by BPAkito** [t4t5/sweetalert#96] opened 2014-10-09 16:18 UTC
Well, it works, but closes immediately after calling it.
Some ideas about this behavior? 
How can i post my code for some help?

Anyone has some clue or idea?

**Comment by djm61** [comment] 2015-05-25 19:46
I'm probably a bit late to the party, but I'll throw my hat into the ring to see if I can help.  To post code, check out this link: [Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by t4t5** [comment] 2017-09-08 09:58
Duplicate of #215

**Closed by t4t5** 2017-09-08 09:58 UTC
Labels: help wanted
