### ISSUE TITLE
Background content moves some pixels towards right when popup is opened

### ISSUE THREAD

**Issue by Gauty89** [t4t5/sweetalert#495] opened 2015-12-13 05:57 UTC
When the popup is opened, background content moves some pixels towards right.  I don't want background content to move. please help

**Comment by JamoCA** [comment] 2016-02-24 16:29
I hope this gets resolved too or someone posts a workaround.  This is a duplicate of this issue (and possibly earlier ones):
https://github.com/t4t5/sweetalert/issues/449

**Comment by t4t5** [comment] 2017-09-08 07:20
This is gone in 2.0

**Closed by t4t5** 2017-09-08 07:20 UTC
