### ISSUE TITLE
Blur on popin display (on Chrome 56)

### ISSUE THREAD

**Issue by ejeanneaubc** [t4t5/sweetalert#671] opened 2017-02-24 10:19 UTC
Hi,

I use this awesome plugin and thank's you for this great tool. I have updated my scripts with the latest version of SweetAlert but now i have some blur when i open the popin. The blur disapear when i move a little the mouse into the popin.

You can see also "this bug" in the demonstration page.

If anyone have any idea ...

Thank's a lot !

Emmanuel.

**Comment by Ishmaeel** [comment] 2017-05-12 08:23
It's a webkit rendering bug. You'll notice the blur in Chrome but not in IE. It is triggered by the 45% stage of the popin animation which uses a scale factor that probably calculates to sub-pixel values.

If you change `scale(1.05)` to  `scale(1)` in the lines below, the blur and other webkit artifacts should disappear:

[Line 379](https://github.com/t4t5/sweetalert/blob/32bd141c24cbc56dd4838ac77c15fa7f96da002d/dist/sweetalert.css#L379)

[Line 380](https://github.com/t4t5/sweetalert/blob/32bd141c24cbc56dd4838ac77c15fa7f96da002d/dist/sweetalert.css#L380)

[Line 393](https://github.com/t4t5/sweetalert/blob/32bd141c24cbc56dd4838ac77c15fa7f96da002d/dist/sweetalert.css#L393)

[Line 394](https://github.com/t4t5/sweetalert/blob/32bd141c24cbc56dd4838ac77c15fa7f96da002d/dist/sweetalert.css#L394)

**Comment by t4t5** [comment] 2017-09-08 16:20
I'm unable to reproduce this bug. Could it have been fixed with the latest 2.0 release? Please reopen if the issue persists.

**Closed by t4t5** 2017-09-08 16:20 UTC

**Comment by Ishmaeel** [comment] 2017-09-09 02:59
Yes, it is fixed with Chrome update 61.
