### ISSUE TITLE
Closing by clicking outside (allowOutsideClick=true) doesn't call callback

### ISSUE THREAD

**Issue by lorensr** [t4t5/sweetalert#299] opened 2015-03-03 04:10 UTC
I'd like to run code after swal is closed, no matter which way it is closed. $50 bounty for merged fix.

**Comment by buraksarica** [comment] 2015-03-11 14:47
I've implemented your request on a fork (did not committed), but it has a downside. If you call swal() again in callback, it interferes with the current one and it doesn't work correctly. May be authors should consider separating the events or adding specific events. (e.g. OnCancelled, OnConfirmed)

**Comment by mcblum** [comment] 2015-03-18 20:25
This is an issue for me as well. Would be great to see a fix.

**Closed** 2015-03-19 15:15 UTC
Labels: WIP

**Comment by mcblum** [comment] 2015-03-19 15:32
Hi. Is it correct to say that clicking outside the alert will trigger the same result as clicking 'cancel'? In my case 'cancel' and 'ok' are both options and so I was hoping that clicking outside the box would trigger neither.

**Comment by t4t5** [comment] 2015-03-19 17:00
@mcblum Yeah, clicking "Cancel" and clicking outside now behaves exactly the same (as it should be really). I guess we should add an option to make them separate though since it might be useful as you pointed out!

**Comment by Codemax999** [comment] 2015-09-18 16:36
This would be a great feature as I am also hoping to be able to click outside the alert and have it dismiss without running the the cancel function. Any updates?

**Comment by lasergoat** [comment] 2017-05-05 16:02
For anyone struggling with the `onOutsideClick` function also calling the `onCancel` a simple hackish workaround is this:

```JSX
<SweetAlert
  show={showConfirm}
  title="Weekly Summary Email"
  text={'....?'}
  showCancelButton
  onCancel={() => this.handleChoice(false)}
  onConfirm={() => this.handleChoice(true)}
  onOutsideClick={() => {
    this.wasOutsideClick = true;
    this.setState({ showConfirm: false })
  }}
  confirmButtonText="Yes, Definitely"
  cancelButtonText="Nope"
/>

// then in handleChoice just do:

  handleChoice(choice) {
    if (this.wasOutsideClick) {
      return;
    }
    // ...

```
